### ISSUE TITLE
Expand %expand to evaluate markdown text in other kernels

### ISSUE THREAD

**Issue by BoPeng** [vatlab/markdown-kernel#5]
For example

```
%expand --in R
```

can 
1. send the markdown text to R
2. let R handles it
3. return expanded markdown

We will need to expand our language module to achieve this but it solves the R-markdown and other markdown problems natively. In particular, it allows almost perfect conversion from `Rmd` to `.ipynb`.

**Comment by BoPeng** [comment]
@gaow What is the function in `knitr` to expand a piece of `Rmd` code by evaluating the expression in it? Basically, I need a function ??? to

```
a <- 1
expanded <- ???('value of a is `r a`')
```
with `expanded` being `value of a is 1`.

I suspect it is something like `knitr::expand`....

**Comment by gaow** [comment]
>What is the function in knitr to expand a piece of Rmd

It is literally `expand` :D 

https://cran.r-project.org/web/packages/knitr/vignettes/knit_expand.html

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/68400982-92294600-013e-11ea-9fd1-c4b64dbfcce1.png)

Thanks, but this is not the `Rmd` syntax, right? Perhaps we need some function in `rmarkdown` package?

**Comment by BoPeng** [comment]
It is not terribly difficult to translate 

```
value of a is `r a`
```
to a markdown cell as

```
%expand --in R
value of a is {a}
```
and call
```
 knit_expand(text=text, delim=c('{', '}'))
```
under the hood, but I suspect that users would be expecting 

```
%expand --in R
value of a is `r a`
```
to work directly.

**Comment by gaow** [comment]
I see ... yes this must be a piece of code in rmarkdown package that does the job; but not a function an end user needs to worry about.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/68402014-48415f80-0140-11ea-92e7-ab73df20020d.png)


I think

```
%expand --in R
value of a is {a}
```
makes sense if we write in Jupyter directly (without thinking of `RMarkdown`), and we can use `knitr_expand(delim=c('{', '}')` to do the job.

Then when we convert a Rmd file to Jupyter, we can do something like

```
%expand `r ` --in R 
value of a is `r a`
```

Problem solved. :-)

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/68407220-cf92d100-0148-11ea-8b9c-a3fde8a3b27e.png)

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/68431746-878ba280-0178-11ea-8c47-79f5db775299.png)

![image](https://user-images.githubusercontent.com/9889312/68431685-6fb41e80-0178-11ea-8ccb-56135d6a1c37.png)
